services:
  shop:
    build: ./shop
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./shop:/code
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./shop/.env

  db:
    image: postgres:15.8
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./shop/.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 3s
      retries: 3

  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - db
