services:
  nginx:
    image: nginx:1.26.2
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./shop/static/:/var/www/static/
      - ./shop/media/:/var/www/media/
    depends_on:
      - shop

  shop:
    build: ./shop
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./shop:/code
      - ./shop/static/:/var/www/static/
      - ./shop/media/:/var/www/media/
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./shop/.env

  db:
    image: postgres:15.8
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./shop/.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 3s
      retries: 3