services:
  shop:
    build: ./shop
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./shop:/code
    depends_on:
      - db
    env_file:
      - ./shop/.env

  db:
    image: postgres:15.8
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
