# Generated by Django 4.2.16 on 2024-12-17 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_owner_product_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='logo',
            field=models.ImageField(default='default-shop-logo.png', upload_to='product/'),
        ),
    ]
