# Generated by Django 4.2.16 on 2024-10-03 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['created_at', 'name'], 'verbose_name': 'Store', 'verbose_name_plural': 'All Stores'},
        ),
    ]
