from shop.settings import *

# for https
# SESSION_COOKIE_SECURE = True
# CSRF_COOKIE_SECURE = True
# CSRF_COOKIE_DOMAIN = '13.36.46.190'
# CSRF_COOKIE_NAME = 'csrf_token'
# SECURE_HSTS_SECONDS = 31536000
# SECURE_SSL_REDIRECT = True
# SECURE_HSTS_INCLUDE_SUBDOMAINS = True
# SECURE_HSTS_PRELOAD = True
DEBUG = False
CSRF_TRUSTED_ORIGINS = ["http://13.36.46.190"]